name: test

on:
  push

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: cmd
      run: |
        uname -a
        curl 'https://api.ipify.org/?format=json'
        git clone https://github.com/cavaliercoder/dmidecode-osx
        make
        ./dmidecode

